[#IOPSC-113] Add IP Addresses
pagopa/io-developer-portal-service-data pull request #14
Opened 2022-11-15 17:06 UTC by LoFrance

We need to retrieve IP Addresses from Cosmos and save on PostgreSQL.

#### List of Changes
- Change Schema: add JSON field to represent a lists of IPs
- Change Jest config
- Change code review pipeline
- SQL: Need to add sql to take IP values from Cosmos (WIP)

#### Motivation and Context
It will be useful to have a table where we can store the authorized IP and retrieve for our checks.

#### How Has This Been Tested?
Will be some jest tests

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-11-16 07:12 UTC, LoFrance reviewed
The insert query doesn't add the `authorizedCIDRS` data.

2022-11-28 13:56 UTC, balanza requested changes
It's better to deploy schema changes and code changes in separated steps to avoid inconsistencies and edge cases.

Can you split these changes in two PRs?

2022-11-28 13:56 UTC, balanza commented on schema/migrations/db/V1__schema.sql
> +    CONSTRAINT servicedata_pkey PRIMARY KEY ("id")
Once applied, we cannot edit sql schema migrations. Instead, we should alter the current schema via a new migration step.

2022-11-29 07:08 UTC, LoFrance commented on models/Domain.ts
> +  authorizedCIDRS: t.interface({ ip: t.readonlyArray(t.string) }),
Because this is a JSON data and I need an object.

2022-11-29 07:09 UTC, LoFrance commented
> It's better to deploy schema changes and code changes in separated steps to avoid inconsistencies and edge cases.
> 
> Can you split these changes in two PRs?

Yep, you're right, I split it in two:

- for DB Schema: https://github.com/pagopa/io-developer-portal-service-data/pull/15
- for Domain and Code: https://github.com/pagopa/io-developer-portal-service-data/pull/16

2022-11-29 07:12 UTC, LoFrance commented on schema/migrations/db/V1__schema.sql
> +    CONSTRAINT servicedata_pkey PRIMARY KEY ("id")
Oh, I guessed to reset the DB however I've added a new v4 migration schema file to do a DROP and ADD a new constraint, unfortunately a Primary Key constraint can't be altered.

2022-11-29 09:58 UTC, closed without merging