[IOPSC-57] Base code for change feed handler
pagopa/io-developer-portal-service-data pull request #4
Opened 2022-09-21 13:56 UTC by LoFrance

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-09-26 10:35 UTC, balanza requested changes

2022-09-26 10:35 UTC, balanza commented on OnServiceChange/handler.ts
> +): Handler => pipe(handler());
```suggestion
): Handler => handler();
```

2022-09-26 10:35 UTC, balanza commented on OnServiceChange/handler.ts
> +  );
It seems the handler does nothing

2022-09-26 12:20 UTC, LoFrance commented
This PR was replaced by https://github.com/pagopa/io-developer-portal-service-data/pull/4

2022-09-26 12:22 UTC, LoFrance commented on OnServiceChange/handler.ts
> +  );
Yes, thanks, next time it's best to handle it with an exception so no documents be skipped

2022-09-28 07:56 UTC, balanza commented on OnServiceChange/handler.ts
> +// TO DO: This is the Handler and it's to be implemented!
```suggestion
```

2022-09-28 09:01 UTC, balanza approved these changes

2022-09-28 11:04 UTC, merged